<?php

namespace PremierBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SousProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousProduitRepository extends EntityRepository
{
}
